reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
reference_os: &reference_os
  'linux'
official_repo: &official_repo
  'DanySK/Thread-Inheritable-Resource-Loader-for-Java'
language: bash
git:
  depth: false
os:
  - osx
  - windows
  - *reference_os
dist: trusty
addons:
  apt:
    packages:
      - graphviz
stages:
  - check
  - test
  - deploy
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - PUBLISH="false"
    - OFFICIAL_REPO_SLUG="DanySK/Thread-Inheritable-Resource-Loader-for-Java"
    - NO_WIN_DEFENDER=`curl "${GRAVIS}.disable-windows-defender.sh" --output .no-defender.sh && source .no-defender.sh`
  matrix:
    - *reference_jdk
matrix:
  exclude:
    - os: *reference_os
      env: *reference_jdk
jobs:
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
        - secure: "EvV1U9xlMFXTP3GSpbhtTXjHMOpO7ALw4Ayp6+VMuYPeW68gDeVoB8YR2D2B8w1tKQ+SReN1ocpGHupQE9WRA5DMadBhhxeN+uPPLX+85yeXxHhI5NpgYy1TdVpXonZeg79ignsp2pMDX3gSSl/ockpll9n+WUl3y9dTxCJ2ifQ1gcrnQxixea775DsjG0DZ5NhoEMQrFNqwIXmHzg8CbD35ZkY3KxiLeeou1AD4iGzkv5gTRWzJ5doEIGbDUaePQ7xi3BorztfcbQJAvfkU4jG9CE/QCvXchD9jbcqq4WxJTM470WJU5Ekw9tWoNoxk321aaAkfV8r/mzxrMCR1tpAehdYWMF+mx2GmnJ56v4V4AWRDa24Nz+W3I4+d1RbYOoFOH86W2/DI9350YnDmNJJRCbtMGFzkcEOzHSF13FEoDwgkh/B2PtmBcjBcpl6onNWDUD3trwVB9d6iR7CKGIzQPSUZqi4XvTBB4DN2oBXbhhWUhHBGNBLGoEW60HY45Cv9eQ4qxKht21L5FSjPSAIfbPXdrZX4qTyDPB01ApShByRSuFQG8cvdRphm7SXsM8IgDejd28phOU0sIb/Mrd0V0xC3TjnWu2gvOKwNEMogTjV/6fOVwwbBtohQjJ9HF3fdLtvzR2Vhda0fPCqEdqdN6Vd1oqAsN1ERMiN3A1w="
        - secure: "coFngfc8MWVVbKGU+KtMcCKjQ8sN8eHzmXF3ZA5G2URO+HDA6udZbewqbfUnOBouiuZGJVxsCNI3rrE3hIy6/wc/UoqXRaXRexSZUyiL5vDihvz0unserdEPM6E2qkqq379q9t67qyiwoymIFyvV8SzWS6V7Sp2/wRAnfQiVbVEe4Yb2RDo4xjIBEFCh6UkgQvbBSe40bHrx925Esij/VSgcUb1S6+EOQb5y/GKaLHqzxG00p1XD+ITy4uL0h8vyWj2Xfpe6+r2jb9FP55OzP30HKty1YMSb2+prB+tf/9qL9HKLeJ3OkTZGDmBzf+Nug0zz/kNdWM+6hIzQBioFxynZXHrHf63s0QBTvEMb06dPqlt9uWYd08CGBgW2zTNNiq91zNGYXLWtNFjI4mHbfoL1bXE7exCTa57FYJBs3on+HuH4JLsQLLfBcrVjaG1AoEaSdP6e44ARG9HSlqadM6KTeENJip/x8hmIjd8O/SpFk1jJzEE9h7DCgKyaT9ziADpV1YaZvpQQUL1Qp2s/aWf1CLru0ZGIjhH+5vYYPuIYZTozbKPqR0V7oA+J2df55vPCPnTfG9/EGW/OZt949vFwIoTtKwWkqCBb0WGpCWeTmJfScZOLr/IucA+3PxA20Uhn4/xuZzu1yKDF11jRt6iy/wUSj+Y1FwseENk9dOs="
        - secure: "ITIbLrxkfMG6u9cO7UqPTExTvKIkHFSbz6YCbzpi5t4eddVRP0Z3ughJpYRGWauSUBFoIDZT0Qka8r2+I6K4z+cmuypNihyPKV5R8aXUpSOrhDVOrtUBJxrL1lhkP6ahni21EhPt8tTH/DIcBMgM8NFIH6JdShTdXrKLSZPhH5+dgMdD3xwKdn25wk1q9XcWhM5nSaNmu8QL77vgFyCWOLevUXB4/5Jm5BElg7Wl8epxrkp0qOY8j+Vxd0ysQTnBJ6Il3rAyN+D/2VtYJPetNEfgyq7vyvElBXmrqE5wC+9oMmg2SUlUAgRxCUPRUA2cwRk1dKn5BHg61P/5LuPu0nb4ZIaYE1FXddKcNXQKEVjZdPHAmLkq3BTMqA5RCtCCQydTNUgMB4fLGGXQ/39QpFHC6F1ae5cpT/rG2cVJaqqnlRScTKqiEYtijgWm988w9d5LJBzySPwzLDtPUrW1gqjCJHYXIDdoUKjBB1yX6PdgZvZ3BsR5QohvdlL3DTs16QBCj8ufomApKYde2H6mbNoiNdgN4DNHI7Nsn+PGu9kmPu6b9+L3p5wYQ/EOz7+t82urflQrZRO6h92zTf52k/RzDnGFIFHvU8Hs47XnhsAex6JSmjuufOr2RAvb64NEKTYo5h236WG4awRok1ErqM1euDIa5g1hZGSnGVoppXQ="
      script:
        - ./gradlew check
    - stage: deploy
      name: "Reports and deployment"
      if: repo = env(OFFICIAL_REPO_SLUG) AND type != pull_request
      os: *reference_os
      env:
        - PUBLISH="true"
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_c97e58f83f35_key -iv $encrypted_c97e58f83f35_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - ./gradlew compileJava
      after_success:
        - ./gradlew publishAllPublicationsToMavenRepository
before_install:
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
script:
  - ./gradlew test
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
