reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
reference_os: &reference_os
  'linux'
language: bash
git:
  depth: false
os:
  - osx
  - windows
  - *reference_os
dist: bionic
addons:
  apt:
    packages:
      - graphviz
stages:
  - check
  - test
  - deploy
env:
  global:
    - TERM=dumb
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - PUBLISH="false"
    - OFFICIAL_REPO_SLUG="DanySK/Thread-Inheritable-Resource-Loader-for-Java"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@1.12"
    - JDK="adopt-openj9@1.12"
matrix:
  exclude:
    - os: *reference_os
      env: *reference_jdk
jobs:
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
      script:
        - ./gradlew check
    - stage: deploy
      name: "Reports and deployment"
      if: repo = env(OFFICIAL_REPO_SLUG) AND type != pull_request
      os: *reference_os
      env:
        - PUBLISH="true"
        # Signing
        - secure: "coFngfc8MWVVbKGU+KtMcCKjQ8sN8eHzmXF3ZA5G2URO+HDA6udZbewqbfUnOBouiuZGJVxsCNI3rrE3hIy6/wc/UoqXRaXRexSZUyiL5vDihvz0unserdEPM6E2qkqq379q9t67qyiwoymIFyvV8SzWS6V7Sp2/wRAnfQiVbVEe4Yb2RDo4xjIBEFCh6UkgQvbBSe40bHrx925Esij/VSgcUb1S6+EOQb5y/GKaLHqzxG00p1XD+ITy4uL0h8vyWj2Xfpe6+r2jb9FP55OzP30HKty1YMSb2+prB+tf/9qL9HKLeJ3OkTZGDmBzf+Nug0zz/kNdWM+6hIzQBioFxynZXHrHf63s0QBTvEMb06dPqlt9uWYd08CGBgW2zTNNiq91zNGYXLWtNFjI4mHbfoL1bXE7exCTa57FYJBs3on+HuH4JLsQLLfBcrVjaG1AoEaSdP6e44ARG9HSlqadM6KTeENJip/x8hmIjd8O/SpFk1jJzEE9h7DCgKyaT9ziADpV1YaZvpQQUL1Qp2s/aWf1CLru0ZGIjhH+5vYYPuIYZTozbKPqR0V7oA+J2df55vPCPnTfG9/EGW/OZt949vFwIoTtKwWkqCBb0WGpCWeTmJfScZOLr/IucA+3PxA20Uhn4/xuZzu1yKDF11jRt6iy/wUSj+Y1FwseENk9dOs="
        # Central
        - secure: "EvV1U9xlMFXTP3GSpbhtTXjHMOpO7ALw4Ayp6+VMuYPeW68gDeVoB8YR2D2B8w1tKQ+SReN1ocpGHupQE9WRA5DMadBhhxeN+uPPLX+85yeXxHhI5NpgYy1TdVpXonZeg79ignsp2pMDX3gSSl/ockpll9n+WUl3y9dTxCJ2ifQ1gcrnQxixea775DsjG0DZ5NhoEMQrFNqwIXmHzg8CbD35ZkY3KxiLeeou1AD4iGzkv5gTRWzJ5doEIGbDUaePQ7xi3BorztfcbQJAvfkU4jG9CE/QCvXchD9jbcqq4WxJTM470WJU5Ekw9tWoNoxk321aaAkfV8r/mzxrMCR1tpAehdYWMF+mx2GmnJ56v4V4AWRDa24Nz+W3I4+d1RbYOoFOH86W2/DI9350YnDmNJJRCbtMGFzkcEOzHSF13FEoDwgkh/B2PtmBcjBcpl6onNWDUD3trwVB9d6iR7CKGIzQPSUZqi4XvTBB4DN2oBXbhhWUhHBGNBLGoEW60HY45Cv9eQ4qxKht21L5FSjPSAIfbPXdrZX4qTyDPB01ApShByRSuFQG8cvdRphm7SXsM8IgDejd28phOU0sIb/Mrd0V0xC3TjnWu2gvOKwNEMogTjV/6fOVwwbBtohQjJ9HF3fdLtvzR2Vhda0fPCqEdqdN6Vd1oqAsN1ERMiN3A1w="
        - secure: "ExQyBk93hS3GaNuplCR+tIhMM3BNVAmvBg2BL6edIGvC38AlljfZwpcoH+aeYWHe+SXi+uMIjndP1KWvkOc/Wj8Dr2CSt3XDWsdt3hLeQzjcV3fsQN4gFtPXzT7bJu+W2vdz5lYM1aQ/R4GvXWpAYRUX+9M8pwGY1BJ4o+4a4ILHTrP7gafdD3uUAA4aobjBQSLOaqmM+tCFTStPJpPxUMvpa5ydYTAhnLnliEAtweS2mwj/lLWZMlALTpGF0/4+QgZpVKHD5UAmS4KdytGvpQyvMiV3ZmQjuhQLVyiuhjMnGUXYEOfhQdWviRBBn9zKgyKlXqQ065R8vfnB7Az0Z2Z4Mwg2GyI/3cyQJ2rewhmpzABYr1iytJjy7Gt9s9Op+HQG4NpxDxvlpV2EaJHxoFJtUTCiUkmpk5jetIQmDrYZlvxoOkSIj67O/gunPRVOY6QFUIRGpDLgdZQa9tVyCmN8roydp8vxj8Re+DGcukdsZ4Nh90w739amPo2zzQ+CFTHhWbkUmjPaM0UQoknsoI18Dbxs+jOw2FucSj4xnlYJ2D72a5J/zisHQMDH3AjPTMO+QF06uqkJvQQGjjyh9bff4/N9GszJ99/f8Ys4RmzFRimk4Zpr1aEcGkT053DO73FssSTpXYqh5QEUtie9Ycw9G3xIXvcr822F+Q7JSLg="
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_c97e58f83f35_key -iv $encrypted_c97e58f83f35_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - ./gradlew sign -x test
      after_success:
        - travis_wait 40 ./gradlew publishAllPublicationsToMavenRepository
before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
script:
  - ./gradlew test
before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
